name: Publish Release

on:
  workflow_dispatch:
  push:
    tags: ["v*"]
    paths-ignore:
      - .github/workflows/*

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v2
      - name: Set up Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: "2.x"
      - name: Get Version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
          path: "plugin.json"
          prop_path: "Version"
      - run: echo ${{steps.version.outputs.prop}}
      - name: Package Release
        run: |
          just pack
      - name: Publish
        uses: softprops/action-gh-release@v2
        # Only release for tags
        # (conditional not necessary because of `on` config, but kept for reference)
        # if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "Flow.Launcher.Plugin.HelloWorldDeno.zip"
          tag_name: "v${{steps.version.outputs.prop}}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
